.PHONY: clean

all: clean

clean:
	find . -name '.DS_Store' -exec rm -f {} \;
	find . -name '*~' -exec rm -f {} \;
    find . -name '*.pyc' -exec rm -f {} \;
    find . -name '*.pyo' -exec rm -f {} \;

