
# Project settings
# =================

## Development server
host: 0.0.0.0
port: 8080

## Ignore the views listed here when generating the static files
views_ignore:
  - theme/header.html
  - theme/post.html
  - main_toc.md

## Ignore the views listed here in the _index
views_list_ignore:
  - theme/header.html
  - theme/post.html
  - main_toc.md

## Enabled pre-processors
pre_processors: 
  - markdown

## Enabled post-processors
post_processors: 
  - pygments

theme_prefix: html

## Constants
GITHUB_URL: https://github.com/lucuma/shake
VERSION: "1.2.0"
GOOGLE_ANALYTICS_CODE: ""
